name: Build Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Checkout termux-packages
        run: |
          git clone -n https://github.com/termux/termux-packages
          git checkout 8a5fe78e76d61ea95f832a3af173706034a76344

      - name: Setup dependencies
        run: |
          sudo apt update
          sudo apt install software-properties-common -y
          sudo add-apt-repository ppa:deadsnakes/ppa -y
          cd termux-packages
          ./scripts/setup-ubuntu.sh

      - name: Build
        run: |
          cd termux-packages
          ./build-package.sh nodejs-lts
        env:
          NDK: /usr/local/lib/android/sdk/ndk/23.1.7779620

      - name: Zip
        run: |
          cd /data/data/com.termux/files/usr
          mkdir -p dist/bin
          mv bin/node dist/bin
          mv bin/npm dist/bin
          mv bin/npx dist/bin
          mv lib dist
          cd dist
          zip -r ../node-v16.14.0-android-arm64.zip .

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: /data/data/com.termux/files/usr/node-v16.14.0-android-arm64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
