name: Build Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Checkout termux-packages
        run: git clone https://github.com/termux/termux-packages

      - name: Setup dependencies
        run: |
          sudo apt update
          sudo apt install software-properties-common -y
          sudo add-apt-repository ppa:deadsnakes/ppa -y
          cd termux-packages
          ./scripts/setup-ubuntu.sh

      - name: Build
        run: |
          cd termux-packages
          ./build-package.sh nodejs-lts
        env:
          NDK: /usr/local/lib/android/sdk/ndk/23.1.7779620

      - name: Get Node version
        run: echo "NODE_VERSION=$(ls termux-packages/output | grep nodejs-lts | sed -ne 's/-[^-]*$//;s/.*_//;p')" >> $GITHUB_ENV

      - name: Zip
        run: |
          cd /data/data/com.termux/files/usr
          mkdir -p dist/bin
          mv bin/node dist/bin
          mv bin/npm dist/bin
          mv bin/npx dist/bin
          mv lib dist
          mv share/doc/nodejs-lts/LICENSE dist
          cd dist
          zip -r ../node-v${NODE_VERSION}-android-arm64.zip .

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: /data/data/com.termux/files/usr/node-v${{ env.NODE_VERSION }}-android-arm64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
